language: go

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - go get github.com/sger/go-archiver
  - go get github.com/sger/go-hashdir
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go vet
  - go test -v
  - $HOME/gopath/bin/goveralls -service=travis-ci 