language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

before_install:
  - cp .netrc ~
  - chmod 600 .netrc
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get -t
  - go get github.com/sger/go-hashdir

script:
  - go vet
  - go test -v
  - $HOME/gopath/bin/goveralls -service=travis-ci 